import Foundation

// Usage: swift tools/generate_emojis.swift /absolute/path/to/NeverSayNo_App_Emojis_2600_no_flags.txt /absolute/path/to/output/EmojiList.swift

extension Character {
    /// Stricter heuristic: actual emoji presentation or ZWJ/VS16 sequences, excluding plain digits/#/*.
    var isActualEmoji: Bool {
        let scalars = self.unicodeScalars
        let hasEmojiPresentation = scalars.contains { $0.properties.isEmojiPresentation }
        let hasVS16 = scalars.contains { $0.value == 0xFE0F }
        let hasZWJ = scalars.contains { $0.value == 0x200D }
        if hasEmojiPresentation || hasVS16 || hasZWJ {
            return true
        }
        // If all scalars are emoji, still exclude ASCII digits/#/* used for keycap sequences when isolated
        let allEmojiScalars = scalars.allSatisfy { $0.properties.isEmoji }
        if allEmojiScalars {
            for s in scalars {
                let v = s.value
                if (v >= 0x30 && v <= 0x39) || v == 0x23 || v == 0x2A { return false }
            }
            return true
        }
        return false
    }

    /// True if the character is solely a Fitzpatrick skin tone modifier (U+1F3FB..U+1F3FF)
    var isSkinToneModifierOnly: Bool {
        for s in self.unicodeScalars {
            let v = s.value
            if v < 0x1F3FB || v > 0x1F3FF { return false }
        }
        return !self.unicodeScalars.isEmpty
    }
}

func extractEmojis(from text: String) -> [String] {
    var seen = Set<String>()
    var result: [String] = []

    // Tokenize by whitespace so we can drop standalone digits/letters from prose
    let separators = CharacterSet.whitespacesAndNewlines
    let rawTokens = text.components(separatedBy: separators).filter { !$0.isEmpty }

    for token in rawTokens {
        // Fast drop: pure ASCII digits (0-9), '#', '*'
        if token.unicodeScalars.allSatisfy({
            let v = $0.value
            return (v >= 0x30 && v <= 0x39) || v == 0x23 || v == 0x2A
        }) {
            continue
        }

        // Determine if token contains at least one emoji-like grapheme cluster
        var hasEmoji = false
        for ch in token {
            if ch.isActualEmoji && !ch.isSkinToneModifierOnly { hasEmoji = true; break }
        }
        if !hasEmoji { continue }

        // Normalize token to concatenation of only emoji-like clusters within it
        var normalized = ""
        for ch in token {
            if ch.isActualEmoji && !ch.isSkinToneModifierOnly {
                normalized.append(ch)
            }
        }
        if normalized.isEmpty { continue }

        if !seen.contains(normalized) {
            seen.insert(normalized)
            result.append(normalized)
        }
    }

    return result
}

func generateSwiftFile(emojis: [String]) -> String {
    var lines: [String] = []
    lines.append("// AUTO-GENERATED FILE. Do not edit manually.\n// Generated by tools/generate_emojis.swift\n")
    lines.append("import Foundation\n")
    lines.append("struct EmojiList {\n    static let allEmojis: [String] = [")

    // Emit in chunks for readability
    let chunkSize = 50
    var currentLineTokens: [String] = []
    for (idx, e) in emojis.enumerated() {
        currentLineTokens.append("\"\(e)\"")
        let isChunkEnd = ((idx + 1) % chunkSize == 0)
        if isChunkEnd {
            lines.append("        " + currentLineTokens.joined(separator: ", ") + ",")
            currentLineTokens.removeAll(keepingCapacity: true)
        }
    }
    if !currentLineTokens.isEmpty {
        lines.append("        " + currentLineTokens.joined(separator: ", "))
    }

    lines.append("    ]\n}")
    lines.append("")
    return lines.joined(separator: "\n")
}

// MARK: - Entry

guard CommandLine.arguments.count >= 3 else {
    fputs("Usage: swift tools/generate_emojis.swift <input_txt_path> <output_swift_path>\n", stderr)
    exit(2)
}

let inputPath = CommandLine.arguments[1]
let outputPath = CommandLine.arguments[2]

do {
    let data = try String(contentsOfFile: inputPath, encoding: .utf8)
    let emojis = extractEmojis(from: data)
    let content = generateSwiftFile(emojis: emojis)

    // Ensure parent directory exists
    let outputURL = URL(fileURLWithPath: outputPath)
    try FileManager.default.createDirectory(at: outputURL.deletingLastPathComponent(), withIntermediateDirectories: true)
    try content.write(to: outputURL, atomically: true, encoding: .utf8)

    fputs("Generated \(emojis.count) emojis to \(outputPath)\n", stderr)
} catch {
    fputs("Error: \(error)\n", stderr)
    exit(1)
}


